workspace(name = "CV_COLLECTIONS")




load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Google Test
http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/release-1.10.0.zip"],
  strip_prefix = "googletest-release-1.10.0",
  sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
)


local_repository(
    name = "third_party",
    path = "../third_party"
)

load("@third_party//:third_party.bzl", "declare_xrepo_third_party_repositories")
declare_xrepo_third_party_repositories()